import { Head } from "fresh/runtime";
import {
  breadcrumbFromCanonical,
  head,
  ROLE,
  SITE_DESCRIPTION,
} from "../lib/head.ts";
import { SAME_AS_URLS } from "../lib/config.ts";
import { proof } from "../lib/proof.ts";
import { toJsonLd } from "../lib/json-ld.ts";

export function SEOHead() {
  const h = head.value;

  return (
    <Head>
      {/* Primary meta */}
      <title>{h.title}</title>
      <meta name="description" content={h.description} />
      <link rel="canonical" href={h.canonical} />
      <meta
        name="robots"
        content={h.noindex ? "noindex, nofollow" : "index, follow"}
      />

      {
        /* Twitter Card — large summary with image. No twitter:site: the
          @antonshubin handle is unverified (#193) — Anton hasn't confirmed
          it, and the Content rule forbids shipping an unverified fact. */
      }
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={h.title} />
      <meta name="twitter:description" content={h.description} />
      <meta name="twitter:image" content={h.ogImage} />

      {
        /* Open Graph. og:image:width/height print only when the page knows
          them (lib/head.ts's PageHead.ogImageWidth/ogImageHeight) — most
          og:images are a 1200x630 PNG generated by `deno task og` (#193,
          scripts/og-images.ts), but routes/hackathons/[slug].tsx points
          ogImage at an arbitrary event photo of unknown size instead. */
      }
      <meta property="og:type" content={h.ogType} />
      <meta property="og:title" content={h.title} />
      <meta property="og:description" content={h.description} />
      <meta property="og:url" content={h.canonical} />
      <meta property="og:image" content={h.ogImage} />
      {h.ogImageWidth && h.ogImageHeight && (
        <>
          <meta property="og:image:width" content={String(h.ogImageWidth)} />
          <meta
            property="og:image:height"
            content={String(h.ogImageHeight)}
          />
        </>
      )}
      <meta property="og:site_name" content="Anton Shubin" />
      <meta property="og:locale" content="en_US" />

      {/* JSON-LD Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: toJsonLd({
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "Person",
                "@id": "https://antonshubin.com/#person",
                "name": "Anton Shubin",
                "givenName": "Anton",
                "familyName": "Shubin",
                "jobTitle": ROLE,
                "description":
                  "I'm a senior full-stack engineer and tech lead. I build and run SaaS products end to end, and you own the code, the servers and the keys from day one. I work fixed price when the scope is fixed and hourly when it's open-ended.",
                "url": "https://antonshubin.com",
                "image": "https://antonshubin.com/img/photo-big.webp",
                "email": "mailto:hello@antonshubin.com",
                "knowsLanguage": ["en", "ru"],
                "knowsAbout": [
                  "Software Architecture",
                  "SaaS Development",
                  "Backend Engineering",
                  "AI Integration",
                  "MCP",
                  "Self-hosted AI Infrastructure",
                  "Cloud Infrastructure",
                  "Platform Engineering",
                  "Infrastructure as Code",
                  "Production Operations",
                  "Observability",
                  "Backup and Disaster Recovery",
                  "Identity and Access Management",
                  "Cloud Cost Optimization",
                  "Linux",
                  "Docker Compose",
                  "Traefik",
                  "Deno",
                  "PostgreSQL",
                  "System Design",
                  "System Performance Optimization",
                  "Technical Leadership",
                  "Architecture Audit",
                  "MCP Server Development",
                  "Founder Advisory",
                  "Codebase Review",
                  "Tech Debt Remediation",
                ],
                "award": [
                  `Upwork ${proof("expert-vetted")}`,
                  `Upwork ${proof("job-success")} Job Success`,
                ],
                // No schema.org property fits the Upwork earnings figure
                // without overclaiming (disambiguatingDescription exists to
                // tell apart similarly-named items, not to state earnings),
                // and the figure is already visible on the page (#186) —
                // left out of structured data entirely rather than misused.
                "sameAs": [...SAME_AS_URLS],
                // schema.org's n-ary-relation pattern: a plain "worksFor":
                // {"@id": "...#org"} has no room for a role, so the value is
                // a Role node that itself points at the org (#193 — Anton is
                // co-founder and CEO of NeatSoft).
                "worksFor": {
                  "@type": "Role",
                  "roleName": "Co-Founder and CEO",
                  "worksFor": { "@id": "https://neatsoft.dev/#org" },
                },
              },
              {
                "@type": "Organization",
                "@id": "https://neatsoft.dev/#org",
                "name": "NeatSoft PTE LTD",
                "url": "https://neatsoft.dev",
                "founder": { "@id": "https://antonshubin.com/#person" },
                "identifier": {
                  "@type": "PropertyValue",
                  "propertyID": "UEN",
                  "value": "202300222R",
                },
              },
              {
                "@type": "WebSite",
                "@id": "https://antonshubin.com/#website",
                "url": "https://antonshubin.com",
                "name": `Anton Shubin — ${ROLE}`,
                // Fixed, not h.description: a WebSite entity describes the
                // site itself and must read the same on every page (#193).
                "description": SITE_DESCRIPTION,
                "inLanguage": "en-US",
                "publisher": { "@id": "https://antonshubin.com/#person" },
              },
              {
                "@type": "BreadcrumbList",
                "@id": `${h.canonical}#breadcrumb`,
                "itemListElement": breadcrumbFromCanonical(
                  h.canonical,
                  h.pageName ?? h.title,
                ),
              },
            ],
          }),
        }}
      />
    </Head>
  );
}
