import { Head } from "fresh/runtime";
import { type HeadTag, seoHeadTags } from "@spy4x/preact-system/seo-head";
import {
  getBreadcrumb,
  head,
  type PageHead,
  ROLE,
  SITE_DESCRIPTION,
} from "../lib/head.ts";
import { breadcrumbListJsonLd } from "@spy4x/platform/universal/seo";
import { LOCATION, X_HANDLE } from "../lib/config.ts";
import { COMPANY } from "../lib/company.ts";
import { EMAIL_ADDRESS, sameAsUrls } from "../lib/profiles.ts";
import { ABOUT_NAME, ABOUT_PATH } from "../lib/about.ts";
import { proof } from "../lib/proof.ts";
import { toJsonLd } from "../lib/json-ld.ts";

/**
 * The meta, canonical, Twitter card and Open Graph tags (#195): the library's
 * `seoHeadTags()`, plus the three tags it has no field for, each placed where
 * it always stood. `twitter:creator` follows `twitter:site`. The handle is the
 * one Anton confirmed on 27 Sep 2026 (#193). `og:image:width`/`height` follow
 * `og:image` and print only when the page knows them (lib/head.ts's
 * `PageHead.ogImageWidth`/`ogImageHeight`): most og:images are a 1200x630 PNG
 * generated by `deno task og` (scripts/og-images.ts), but
 * routes/hackathons/[slug].tsx points `ogImage` at an event photo of unknown
 * size instead. No `jsonLd` goes in: the site's graph is rendered below
 * through `toJsonLd`, which escapes more than the library's `jsonLdText`.
 */
export function headTags(h: PageHead): HeadTag[] {
  const tags = seoHeadTags({
    title: h.title,
    description: h.description,
    canonical: h.canonical,
    noindex: h.noindex,
    ogImage: h.ogImage,
    ogType: h.ogType,
    siteName: "Anton Shubin",
    locale: "en_US",
    twitterSite: X_HANDLE,
  });
  const after = (key: string, value: string, extra: HeadTag[]) => {
    const index = tags.findIndex((tag) => tag.attrs[key] === value);
    if (index === -1) throw new Error(`seoHeadTags() emitted no ${value}`);
    tags.splice(index + 1, 0, ...extra);
  };
  after("name", "twitter:site", [
    { tag: "meta", attrs: { name: "twitter:creator", content: X_HANDLE } },
  ]);
  if (h.ogImageWidth && h.ogImageHeight) {
    after("property", "og:image", [
      {
        tag: "meta",
        attrs: { property: "og:image:width", content: String(h.ogImageWidth) },
      },
      {
        tag: "meta",
        attrs: {
          property: "og:image:height",
          content: String(h.ogImageHeight),
        },
      },
    ]);
  }
  return tags;
}

/**
 * Renders one tag without a `key`: the library's own `SEOHead` keys each tag
 * by its index, and Fresh's `<Head>` prints a key as `data-key` and
 * de-duplicates head elements by it across every `<Head>` on the page.
 */
function renderTag(tag: HeadTag) {
  if (tag.tag === "title") return <title>{tag.text}</title>;
  if (tag.tag === "link") return <link {...tag.attrs} />;
  if (tag.tag === "meta") return <meta {...tag.attrs} />;
  throw new Error(`headTags() emitted an unexpected <${tag.tag}>`);
}

export function SEOHead() {
  const h = head.value;
  const path = new URL(h.canonical).pathname;
  // `/about` is the one page that is Anton's profile (#294, SEO 1): it gets
  // the site's only ProfilePage. The home page is an offer page, so it gets a
  // plain WebPage about the Person and no BreadcrumbList, whose single "Home"
  // item says nothing (#269).
  const isHome = path === "/";
  const isAbout = path === ABOUT_PATH;
  const breadcrumb = breadcrumbListJsonLd(
    h.canonical,
    getBreadcrumb(h.canonical, h.pageName ?? h.title),
  );
  const pageNodes = isHome
    ? [{
      "@type": "WebPage",
      "@id": "https://antonshubin.com/#webpage",
      "url": "https://antonshubin.com/",
      "name": h.title,
      "about": { "@id": "https://antonshubin.com/#person" },
      "isPartOf": { "@id": "https://antonshubin.com/#website" },
    }]
    : isAbout
    ? [{
      "@type": "ProfilePage",
      "@id": `${h.canonical}#profile`,
      "url": h.canonical,
      "name": ABOUT_NAME,
      "mainEntity": { "@id": "https://antonshubin.com/#person" },
      "isPartOf": { "@id": "https://antonshubin.com/#website" },
      "breadcrumb": { "@id": breadcrumb["@id"] },
    }, breadcrumb]
    : [breadcrumb];
  // The booking page is the site's contact page (#272): a ContactPage node
  // says so to search engines and AI crawlers. No ScheduleAction, no review.
  const isBooking = path === "/book";

  return (
    <Head>
      {headTags(h).map(renderTag)}

      {
        /* JSON-LD Structured Data: site data, so it stays here, and through
          toJsonLd, which escapes more than the library's jsonLdText. */
      }
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: toJsonLd({
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "Person",
                "@id": "https://antonshubin.com/#person",
                "name": "Anton Shubin",
                "alternateName": "spy4x",
                "givenName": "Anton",
                "familyName": "Shubin",
                "jobTitle": ROLE,
                "description":
                  "I'm a senior full-stack engineer and tech lead. I build and run SaaS products end to end, and you own the code, the servers and the keys from day one. I work fixed price when the scope is fixed and hourly when it's open-ended.",
                "url": "https://antonshubin.com",
                "image": "https://antonshubin.com/img/photo-big.webp",
                "email": `mailto:${EMAIL_ADDRESS}`,
                "contactPoint": {
                  "@type": "ContactPoint",
                  "contactType": "sales",
                  "email": EMAIL_ADDRESS,
                  "url": "https://antonshubin.com/book",
                  "availableLanguage": ["en", "ru"],
                },
                "knowsLanguage": ["en", "ru"],
                "knowsAbout": [
                  "Software Architecture",
                  "SaaS Development",
                  "Backend Engineering",
                  "AI Integration",
                  "MCP",
                  "Self-hosted AI Infrastructure",
                  "Cloud Infrastructure",
                  "Platform Engineering",
                  "Infrastructure as Code",
                  "Production Operations",
                  "Observability",
                  "Backup and Disaster Recovery",
                  "Identity and Access Management",
                  "Cloud Cost Optimization",
                  "Linux",
                  "Docker Compose",
                  "Traefik",
                  "Deno",
                  "PostgreSQL",
                  "System Design",
                  "System Performance Optimization",
                  "Technical Leadership",
                  "Architecture Audit",
                  "MCP Server Development",
                  "Founder Advisory",
                  "Codebase Review",
                  "Tech Debt Remediation",
                ],
                "award": [
                  `Upwork ${proof("expert-vetted")}`,
                  `Upwork ${proof("job-success")} Job Success`,
                ],
                "homeLocation": { "@type": "Place", "name": LOCATION },
                // No schema.org property fits the Upwork earnings figure
                // without overclaiming (disambiguatingDescription exists to
                // tell apart similarly-named items, not to state earnings),
                // and the figure is already visible on the page (#186) —
                // left out of structured data entirely rather than misused.
                "sameAs": sameAsUrls,
                // schema.org's n-ary-relation pattern: a plain "worksFor":
                // {"@id": "...#org"} has no room for a role, so the value is
                // a Role node that itself points at the org (#193 — Anton is
                // co-founder and CEO of NeatSoft).
                "worksFor": {
                  "@type": "Role",
                  "roleName": "Co-Founder and CEO",
                  "worksFor": { "@id": "https://neatsoft.dev/#org" },
                },
              },
              {
                "@type": "Organization",
                "@id": "https://neatsoft.dev/#org",
                "name": COMPANY.name,
                "url": "https://neatsoft.dev",
                "founder": { "@id": "https://antonshubin.com/#person" },
                "identifier": {
                  "@type": "PropertyValue",
                  "propertyID": "UEN",
                  "value": COMPANY.uen,
                },
              },
              {
                "@type": "WebSite",
                "@id": "https://antonshubin.com/#website",
                "url": "https://antonshubin.com",
                // The short name Google shows above a result (#269).
                "name": "Anton Shubin",
                "alternateName": "antonshubin.com",
                // Fixed, not h.description: a WebSite entity describes the
                // site itself and must read the same on every page (#193).
                "description": SITE_DESCRIPTION,
                "inLanguage": "en-US",
                "publisher": { "@id": "https://antonshubin.com/#person" },
              },
              ...pageNodes,
              ...(isBooking
                ? [{
                  "@type": "ContactPage",
                  "@id": `${h.canonical}#webpage`,
                  "url": h.canonical,
                  "name": h.title,
                  "isPartOf": { "@id": "https://antonshubin.com/#website" },
                  "about": { "@id": "https://antonshubin.com/#person" },
                  "breadcrumb": { "@id": `${h.canonical}#breadcrumb` },
                  "inLanguage": "en-US",
                }]
                : []),
            ],
          }),
        }}
      />
    </Head>
  );
}
