import { signal } from "@preact/signals";
import { BASE_URL } from "./config.ts";

export interface PageHead {
  title: string;
  description: string;
  canonical: string;
  ogImage: string;
  /**
   * `ogImage`'s pixel size, when known — printed as `og:image:width`/
   * `og:image:height` (components/SEOHead.tsx). Every generated OG PNG
   * (scripts/og-images.ts) is exactly 1200x630, but `ogImage` isn't always
   * one of those: routes/hackathons/[slug].tsx points it at an arbitrary
   * event photo instead, so a page that does that must leave these unset
   * (or explicitly clear them — DEFAULTS below sets 1200x630, and a page
   * that changes `ogImage` without also touching these would otherwise
   * inherit the wrong size, `resetHead()` notwithstanding).
   */
  ogImageWidth?: number;
  ogImageHeight?: number;
  ogType: "profile" | "article" | "website" | "service";
  noindex?: boolean;
  /**
   * The bare page name for the breadcrumb (visible nav and JSON-LD
   * BreadcrumbList) — "Ship It Today", not "Ship It Today — Anton Shubin".
   * `title` carries the " — Anton Shubin" (or "| ROLE") suffix meant for the
   * browser tab and search results, which reads wrong as a breadcrumb
   * segment. Falls back to `title` when a page hasn't set it (#193 fixed
   * this for the pages this issue touches; other pages still pass their
   * full title here, unchanged from before).
   */
  pageName?: string;
}

/**
 * The label I lead with everywhere: hero, `<title>`, description, Person
 * JSON-LD, llms files. "Fractional CTO" is one service in lib/catalog.ts, not
 * a label.
 */
export const ROLE = "Senior Full-Stack Engineer & Tech Lead";

const DEFAULTS: PageHead = {
  title: `Anton Shubin | ${ROLE}`,
  // lib/head.test.ts regex-matches this literal directly (it can't import
  // ./config.ts's Deno.env read under deno task test's narrow permissions),
  // so it stays a literal string here rather than a reference to a constant.
  description:
    "I'm a senior full-stack engineer and tech lead. I build and run SaaS products end to end, and you own the code, the servers and the keys from day one.",
  canonical: "https://antonshubin.com/",
  // 1200x630 landscape (#193) — replaces the 1200x1800 portrait photo, which
  // LinkedIn, X, Facebook and Slack all crop badly. Generated by
  // `deno task og` (scripts/og-images.ts); see AGENTS.md "OG image
  // generator".
  ogImage: "https://antonshubin.com/img/og/default.png",
  ogImageWidth: 1200,
  ogImageHeight: 630,
  ogType: "profile",
};

/**
 * The WebSite JSON-LD node's `description` (components/SEOHead.tsx). Fixed
 * on purpose — unlike `PageHead.description` (the per-page meta description),
 * a WebSite entity describes the site itself, so it must read the same on
 * every page (#193). Derived from `DEFAULTS`, not a second literal, so the
 * two can't drift apart.
 */
export const SITE_DESCRIPTION = DEFAULTS.description;

export const head = signal<PageHead>({ ...DEFAULTS });

export function resetHead() {
  head.value = { ...DEFAULTS };
}

// --------------- Breadcrumb helpers ---------------

function humanize(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/**
 * Generate a BreadcrumbList itemListElement array from a canonical URL.
 * Used by the JSON-LD structured data in _app.tsx.
 *
 * Href values are WITHOUT trailing slashes (e.g. "/blog" not "/blog/").
 * A [slug] route 404s when the path ends in a trailing slash
 * (e.g. /work/smartlite/ 404s, /work/smartlite is 200), so
 * canonical values, breadcrumb hrefs and sitemap loc values are all
 * written without a trailing slash. The root "/" is the only exception
 * (kept for correctness).
 */
export function breadcrumbFromCanonical(
  canonical: string,
  pageName: string,
) {
  const segments = new URL(canonical).pathname.split("/").filter(Boolean);

  const items: unknown[] = [
    { "@type": "ListItem", position: 1, name: "Home", item: `${BASE_URL}/` },
  ];

  let acc = "";
  segments.forEach((seg, idx) => {
    acc += "/" + seg;
    const isLast = idx === segments.length - 1;
    items.push({
      "@type": "ListItem",
      position: idx + 2,
      name: isLast ? pageName : humanize(seg),
      item: `${BASE_URL}${acc}`,
    });
  });

  return items;
}

/**
 * Generate a flat breadcrumb array for the visible <nav> in component/Breadcrumb.tsx.
 * Returns [{ name, href? }, ...] where the last item has no href.
 *
 * Uses URL.pathname to strip protocol/domain/port/hash/query — immune to
 * trailing-slash edge cases and DOMAIN env-var mismatches.
 * Href values are WITHOUT trailing slashes (e.g. "/blog" not "/blog/"),
 * matching the rest of the site. Only "/" keeps its slash.
 */
export function getBreadcrumb(
  canonical: string,
  pageName: string,
): { name: string; href?: string }[] {
  const segments = new URL(canonical).pathname.split("/").filter(Boolean);

  const items: { name: string; href?: string }[] = [{
    name: "Home",
    href: "/",
  }];

  let acc = "";
  segments.forEach((seg, idx) => {
    acc += "/" + seg;
    const isLast = idx === segments.length - 1;
    items.push({
      name: isLast ? pageName : humanize(seg),
      href: isLast ? undefined : acc,
    });
  });

  return items;
}
