name: Deploy
'on':
  push:
    branches:
      - main
      - test-deploy
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn install --frozen-lockfile --non-interactive
      - name: Deploy
        run: yarn firebase deploy --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
